name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET Project
        run: dotnet publish -c Release -o release --nologo

      # Changes the base-tag in index.html from '/' to 'timekeeper' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/timekeeper\/" \/>/g' release/wwwroot/index.html

      # Add .nojekyll file to tell GitHub pages not to run Jekyll
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
